### PR TITLE
new scripts

### PR DESCRIPTION
**Pull request by Quirinwierer**

### CODE REVIEW

**Review by unbekanntes-pferd — CHANGES_REQUESTED** [review]
please adhere to naming standards (e.g. create_personal_rooms.py)

**Review by unbekanntes-pferd — CHANGES_REQUESTED** [review]
variable name room_tupel is unclear - please update to better naming.
Is it a tuple? 
In that case, it should be instantiated using () instead of [].
Ideally, create a model for the expected process entity using pydantic BaseModel.

**Comment by Quirinwierer** [comment]
naming updated, 
room_tupel renamed,
blank lines removed

**Review by unbekanntes-pferd — APPROVED** [review]
Great, thanks!

**Pull request merged**
